Resources:
  CloudFormationUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "CloudFormationDeployUser"

  CloudFormationUserPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "CloudFormationDeployPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "cloudformation:CreateChangeSet"
              - "cloudformation:CreateStack"
              - "cloudformation:DescribeChangeSet"
              - "cloudformation:DescribeStackEvents"
              - "cloudformation:DescribeStacks"
              - "cloudformation:ExecuteChangeSet"
              - "cloudformation:ListChangeSets"
              - "cloudformation:UpdateStack"
              - "cloudformation:DeleteStack"
              - "cloudformation:GetTemplate"
              - "cloudformation:ValidateTemplate"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "iam:PassRole"
            Resource: "*"
            Condition:
              StringEquals:
                "iam:PassedToService": "cloudformation.amazonaws.com"
          - Effect: "Allow"
            Action:
              - "s3:GetObject"
              - "s3:ListBucket"
              - "s3:PutObject" 
            Resource:
              - "arn:aws:s3:::drankio-api-cloudformation-bucket/*"
              - "arn:aws:s3:::drankio-api-cloudformation-bucket"

  YourS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "drankio-api-cloudformation-bucket"
